"""database done

Revision ID: 595040bf6059
Revises: 1a9945e4fecf
Create Date: 2021-05-20 22:19:17.123000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595040bf6059'
down_revision = '1a9945e4fecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coin_name', table_name='coin')
    op.create_index(op.f('ix_coin_name'), 'coin', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_name'), table_name='coin')
    op.create_index('ix_coin_name', 'coin', ['name'], unique=False)
    # ### end Alembic commands ###
