"""tableeees

Revision ID: d1d900976f79
Revises: 
Create Date: 2021-05-24 22:22:08.086000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d900976f79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coinid', sa.String(length=140), nullable=True),
    sa.Column('symbol', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_coinid'), 'coin', ['coinid'], unique=False)
    op.create_index(op.f('ix_coin_name'), 'coin', ['name'], unique=False)
    op.create_index(op.f('ix_coin_price'), 'coin', ['price'], unique=False)
    op.create_index(op.f('ix_coin_symbol'), 'coin', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_symbol'), table_name='coin')
    op.drop_index(op.f('ix_coin_price'), table_name='coin')
    op.drop_index(op.f('ix_coin_name'), table_name='coin')
    op.drop_index(op.f('ix_coin_coinid'), table_name='coin')
    op.drop_table('coin')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
